tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "status-danger-text": "#DC2626",
        "sidebar-gradient-start": "#082F75",
        "inverse-surface": "#2d3134",
        "text-primary": "#0F172A",
        outline: "#747684",
        "on-primary-fixed": "#00164d",
        "secondary-container": "#95b1ff",
        surface: "#f7f9fd",
        "on-tertiary-fixed-variant": "#812800",
        "outline-variant": "#c4c5d5",
        error: "#ba1a1a",
        "on-background": "#181c1f",
        "text-secondary": "#64748B",
        "surface-bright": "#f7f9fd",
        "on-error": "#ffffff",
        "divider-gray": "#EDF2F7",
        "sidebar-gradient-end": "#0B3EA9",
        "status-info-text": "#2563EB",
        "light-blue-bg": "#EFF6FF",
        "error-container": "#ffdad6",
        "border-gray": "#E5E7EB",
        "on-secondary-container": "#234288",
        "inverse-on-surface": "#eff1f5",
        "surface-container": "#eceef2",
        "on-secondary-fixed": "#001848",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-container": "#832900",
        "surface-dim": "#d8dade",
        "text-muted": "#94A3B8",
        "surface-container-highest": "#e0e3e6",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#244389",
        "surface-tint": "#3057c1",
        "primary-container": "#0b3ea9",
        "on-surface": "#181c1f",
        "status-info-bg": "#DBEAFE",
        "status-success-text": "#15803D",
        "on-surface-variant": "#434653",
        "on-tertiary-container": "#ff9e7a",
        "on-secondary": "#ffffff",
        "hover-blue": "#1D4ED8",
        "status-danger-bg": "#FEE2E2",
        "status-warning-text": "#D97706",
        "on-primary-fixed-variant": "#093da8",
        "secondary-fixed": "#dae2ff",
        "on-tertiary-fixed": "#380d00",
        "status-warning-bg": "#FEF3C7",
        "inverse-primary": "#b5c4ff",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#ffb59b",
        secondary: "#3f5ba3",
        "on-primary-container": "#9eb3ff",
        background: "#f7f9fd",
        "status-success-bg": "#DCFCE7",
        "surface-container-low": "#f2f4f8",
        "primary-fixed-dim": "#b5c4ff",
        "surface-variant": "#e0e3e6",
        "surface-container-high": "#e6e8ec",
        primary: "#00297d",
        "surface-container-lowest": "#ffffff",
        tertiary: "#5d1b00",
        "secondary-fixed-dim": "#b2c5ff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "base-8": "8px",
        "sidebar-width": "260px",
        "base-12": "12px",
        "base-32": "32px",
        "base-4": "4px",
        "navbar-height": "80px",
        "grid-unit": "8px",
        "section-gap": "32px",
        "base-24": "24px",
        "base-16": "16px",
        "container-padding": "32px",
        "card-gap": "24px",
      },
      fontFamily: {
        "sidebar-menu": ["Inter"],
        metadata: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        "section-title": ["Inter"],
        "page-title": ["Inter"],
        "card-title": ["Inter"],
        "table-text": ["Inter"],
        "badge-text": ["Inter"],
      },
      fontSize: {
        "sidebar-menu": ["15px", { lineHeight: "22px", fontWeight: "500" }],
        metadata: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        body: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        label: ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "section-title": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "page-title": ["36px", { lineHeight: "43px", fontWeight: "700" }],
        "card-title": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "table-text": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "badge-text": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
};
